version: '3.3'
services:
  bot:
    build:
      context: ./
    depends_on:
      - db-aB
    restart: always
    environment:
      DCtoken: ${DISCORD_BOT_TOKEN}
      DBHost: db-aB
      DBName: agentBlack
      DBUsername: agentBlack
      DBPassword: ${DB_PASSWORD}
      token_uptime: ${TOKEN_UPTIME}
      sentryLink: ${SENTRY_LINK}
  db-aB:
    image: mariadb:latest
    restart: always
    ports:
      - "${DB_IP}:${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
      MYSQL_DATABASE: agentBlack
      MYSQL_USER: agentBlack
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - default
      - grafana_exposed

networks:
  grafana_exposed:
    external: true

volumes:
  db_data:
